name: nutriscore-discordance
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11.15
  - pandas=2.3.2
  - numpy=2.2.6
  - scikit-learn=1.6.1
  - xgboost=3.0.4
  - lightgbm=4.6.0
  - optuna=4.8.0
  - shap=0.48.0
  # R
  - r-base=4.5.2
  - r-tidyverse=2.0.0
  - r-lme4=2.0.1
  - r-lmertest=3.2.1
  - r-performance=0.17.0
  - r-ppcor=1.1
  - r-boot=1.3_32
  - r-ggplot2=4.0.1
  - r-ggalluvial=0.12.6
  - r-ggnewscale=0.5.2
  - r-patchwork=1.3.2
  - r-cowplot=1.2.0
  - r-ggrepel=0.9.8
  - r-sf=1.1_1
  - r-rnaturalearth=1.2.0
  - r-scales=1.4.0
  - r-showtext=0.9_8
  - r-janitor=2.2.1
  
