name: nutriscore-discordance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - r-base=4.5.2
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - xgboost
  - lightgbm
  - shap
  - optuna
  
